const album = [
    {
        id: 1,
        image: "https://m.media-amazon.com/images/I/81JoImtwFhL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Michael Jackson",
        album: "Thriller",
        year: 1982,
        genre: "pop, post-disco, funk, rock",
        sales: "70 million",
        desc: "Thriller is the sixth studio album by American singer and songwriter Michael Jackson, released on November 30, 1982, by Epic Records. It was produced by Quincy Jones, who had previously worked with Jackson on his 1979 album Off the Wall. Jackson wanted to create an album where every song was a killer. With the ongoing backlash against disco music at the time, he moved in a new musical direction, resulting in a mix of pop, post-disco, rock, funk, and R&B sounds. Thriller foreshadows the contradictory themes of Jackson's personal life, as he began using a motif of paranoia and darker themes. The album features a single guest appearance, with Paul McCartney becoming the first artist to be credited as a featured artist on one of Jackson's albums. Recording took place from April to November 1982 at Westlake Recording Studios in Los Angeles, California, with a production budget of $750,000.",
        info: "https://en.wikipedia.org/wiki/Thriller_(album)"
    },
    {
        id: 2,
        image: "https://m.media-amazon.com/images/I/41ycCPp6guL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "AC/DC",
        album: "Back in Black",
        year: 1980,
        genre: "hard rock",
        sales: "50 million",
        desc: "Back in Black is the seventh studio album by Australian rock band AC/DC. It was released on 25 July 1980 by Albert Productions and Atlantic Records. It is the band's first album to feature lead singer Brian Johnson, following the death of previous lead singer Bon Scott. After the commercial breakthrough of their 1979 album Highway to Hell, AC/DC was planning to record a follow-up, but in February 1980, Scott died from alcohol poisoning after a drinking binge. Instead of disbanding, they decided to continue on and recruited Johnson, who was previously vocalist for Geordie.",
        info: "https://en.wikipedia.org/wiki/Back_in_Black"
    },
    {
        id: 3,
        image: "https://m.media-amazon.com/images/I/81wtlU+UrxL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Whitney Houston",
        album: "The Bodyguard",
        year: 1992,
        genre: "r&b, soul, pop, soundtrack",
        sales: "45 million",
        desc: "The Bodyguard: Original Soundtrack Album is a soundtrack album from the film of the same name, released on November 17, 1992, by Arista Records. The album's first side (in its original LP and cassette formats) features songs recorded by American singer Whitney Houston, who starred in the film, while side two features the work of various artists. Houston and Clive Davis were co-executive producers of the record.",
        info: "https://en.wikipedia.org/wiki/The_Bodyguard_(soundtrack)"
    },
    {
        id: 4,
        image: "https://m.media-amazon.com/images/I/A1paB3RNigL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Eagles",
        album: "Greatest Hits (1971–1975)",
        year: 1976,
        genre: "country rock, soft rock, folk rock",
        sales: "44 million",
        desc: "Their Greatest Hits (1971–1975) is the first compilation album by the American rock band the Eagles, released by Asylum Records on February 17, 1976. It contains a selection of songs from the band's first four albums, which were released from 1972 to 1975. On the U.S. Billboard 200 chart, the album reached number one, where it stayed for five weeks.",
        info: "https://en.wikipedia.org/wiki/Their_Greatest_Hits_(1971%E2%80%931975)"
    },
    {
        id: 5,
        image: "https://m.media-amazon.com/images/I/51LJv7pBMaL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Pink Floyd",
        album: "The Dark Side of the Moon",
        year: 1973,
        genre: "progressive rockpsychedelia",	
        sales: "44 million",
        desc: "The Dark Side of the Moon is the eighth studio album by the English rock band Pink Floyd, released on 1 March 1973 by Harvest Records. Primarily developed during live performances, the band premiered an early version of the suite several months before recording began. The record was conceived as an album that focused on the pressures faced by the band during their arduous lifestyle, and dealing with the apparent mental health problems suffered by former band member Syd Barrett, who departed the group in 1968. New material was recorded in two sessions in 1972 and 1973 at EMI Studios (now Abbey Road Studios) in London.",
        info: "https://en.wikipedia.org/wiki/The_Dark_Side_of_the_Moon"
    },
    {
        id: 6,
        image: "https://m.media-amazon.com/images/I/91eh6ApLnzL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Eagles",
        album: "Hotel California",
        year: 1976,
        genre: "soft rock",
        sales: "42 million",
        desc: "Hotel California is the fifth studio album by American rock band Eagles. Released on December 8, 1976, by Asylum Records, Hotel California was recorded by Bill Szymczyk at the Criteria and Record Plant studios between March and October 1976. It was the band's first album with guitarist Joe Walsh, who had replaced founding member Bernie Leadon, and is the last album to feature founding bassist Randy Meisner. The front cover is a photograph of the Beverly Hills Hotel by David Alexander.",
        info: "https://en.wikipedia.org/wiki/Hotel_California_(Eagles_album)"
    },
    {
        id: 7,
        image: "https://m.media-amazon.com/images/I/81GJ7rqSoeL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Shania Twain",
        album: "Come On Over",
        year: 1997,
        genre: "country, pop",
        sales: "40 million",
        desc: "Come On Over is the third studio album recorded by Canadian country music singer Shania Twain. It was released on November 4, 1997, and became the best-selling country album, the best selling album by a Canadian and is recognized by Guinness World Records as the biggest-selling studio album by a solo female artist, and the best-selling album in the USA by a solo female artist. It is the ninth all-time best-selling album in the United States, and worldwide. It is also the sixteenth best-selling album in the United Kingdom.",
        info: "https://en.wikipedia.org/wiki/Come_On_Over"
    },
    {
        id: 8,
        image: "https://m.media-amazon.com/images/I/71BekDJBb3L._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Fleetwood Mac",
        album: "Rumours",
        year: 1977,
        genre: "soft rock",
        sales: "40 million",
        desc: "Rumours is the eleventh studio album by British-American rock band Fleetwood Mac, released on 4 February 1977 by Warner Bros. Records. Largely recorded in California in 1976, it was produced by the band with Ken Caillat and Richard Dashut. The band wanted to expand on the commercial success of their self-titled 1975 album. The group recorded the album in the aftermath of relationship breakups among its members and heavy drug use, both of which shaped the album's lyrics.",
        info: "https://en.wikipedia.org/wiki/Rumours_(album)"
    },
    {
        id: 9,
        image: "https://m.media-amazon.com/images/I/71N6U8pBMQL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Bee Gees / Various Artists",
        album: "Saturday Night Fever",
        year: 1977,
        genre: "disco",
        sales: "40 million",
        desc: "Saturday Night Fever is the soundtrack album from the 1977 film Saturday Night Fever starring John Travolta. The soundtrack was released on November 15, 1977. It is one of the best-selling albums in history, and remains the second-biggest-selling soundtrack of all time, after The Bodyguard, selling over 40 million copies worldwide.",
        info: "https://en.wikipedia.org/wiki/Saturday_Night_Fever_(soundtrack)"
    }, 
    {
        id: 10,
        image: "https://m.media-amazon.com/images/I/81aUUro+3oL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Various Artists",
        album: "Grease",
        year: 1978,
        genre: "rock and roll",
        sales: "38 million",
        desc: "Grease: The Original Soundtrack from the Motion Picture is the original motion picture soundtrack for the 1978 film Grease. It was originally released by RSO Records and subsequently re-issued by Polydor Records in 1984 and 1991. It has sold approximately 38 million copies worldwide, making it one of the best-selling albums of all time, also ranking amongst the biggest selling soundtrack albums of all time. The song 'You're the One That I Want' was a US and UK No. 1 for stars John Travolta and Olivia Newton-John.",
        info: "https://en.wikipedia.org/wiki/Grease:_The_Original_Soundtrack_from_the_Motion_Picture"
    },
    {
        id: 11,
        image: "https://m.media-amazon.com/images/I/81evsr3Oq0L._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Led Zeppelin",
        album: "Led Zeppelin IV",
        year: 1971,
        genre: "hard rock, heavy metal, folk rock",
        sales: "37 million",
        desc: "The untitled fourth studio album by the English rock band Led Zeppelin, commonly known as Led Zeppelin IV, was released on 8 November 1971 by Atlantic Records. It was produced by guitarist Jimmy Page and recorded between December 1970 and February 1971, mostly in the country house Headley Grange. The album is notable for featuring 'Stairway to Heaven', which has been described as the band's signature song.",
        info: "https://en.wikipedia.org/wiki/Led_Zeppelin_IV"
    },
    {
        id: 12,
        image: "https://m.media-amazon.com/images/I/71K9CbNZPsL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Michael Jackson",
        album: "Bad",
        year: 1987,
        genre: "pop, r&b, funk and rock",
        sales: "35 million",
        desc: "Bad is the seventh studio album by American singer and songwriter Michael Jackson. It was released on August 31, 1987, by Epic Records, nearly five years after Jackson's previous album, Thriller (1982). Written and recorded between January 1985 and July 1987, Bad was the third and final collaboration between Jackson and producer Quincy Jones, with Jackson co-producing and composing all but two tracks. Jackson notably adopted an edgy look and sound with Bad, departing from his signature groove-based style and high-pitched vocals. The album incorporates pop, rock, funk, R&B, dance, soul, and hard rock styles. Jackson also experimented with newer recording technology, including digital synthesizers and drum machines, resulting in a sleeker and more aggressive sound. Lyrical themes on the album include media bias, paranoia, racial profiling, romance, self-improvement, and world peace. The album features appearances from Siedah Garrett and Stevie Wonder.",
        info: "https://en.wikipedia.org/wiki/Bad_(album)"
    },
    {
        id: 13,
        image: "https://m.media-amazon.com/images/I/71q5vse3PwL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Alanis Morissette",
        album: "Jagged Little Pill",
        year: 1995,
        genre: "alternative rock",
        sales: "33 million",
        desc: "Jagged Little Pill is the third studio album by Canadian singer Alanis Morissette, released on June 13, 1995, through Maverick. It was her first album to be released worldwide. It marked a stylistic departure from the dance-pop sound of her first two albums, Alanis (1991) and Now Is the Time (1992). Morissette began work on the album after moving from her hometown Ottawa to Toronto, making little progress until she traveled to Los Angeles, where she met producer Glen Ballard. Morissette and Ballard had an instant connection and began co-writing and experimenting with sounds. The experimentation resulted in an alternative rock album that takes influence from post-grunge and pop rock, and features guitars, keyboards, drum machines, and harmonica. The lyrics touch upon themes of aggression, menstruation, and unsuccessful relationships, while Ballard introduced a pop sensibility to Morissette's angst. The title of the album is taken from a line in the first verse of the song 'You Learn'.",
        info: "https://en.wikipedia.org/wiki/Jagged_Little_Pill"
    }, 
    {
        id: 14,
        image: "https://m.media-amazon.com/images/I/61vqvClLxoL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Celine Dion",
        album: "Falling into You",
        year: 1996,
        genre: "pop, soft rock",
        sales: "32 million",
        desc: "Falling into You is the fourth English-language studio album by Canadian singer Celine Dion, released on 11 March 1996 by Columbia/Epic Records. The follow-up to her commercially successful album The Colour of My Love (1993) and French-language D'eux (1995), Falling into You showed a further progression of Dion's music. Throughout the project she collaborated with Jim Steinman, who wrote and produced 'It's All Coming Back to Me Now', among others. Several songs were produced by David Foster, including Diane Warren's 'Because You Loved Me'. In total, Dion worked on the album with fourteen producers and a variety of songwriters and musicians.",
        info: "https://en.wikipedia.org/wiki/Falling_into_You"
    }, 
    {
        id: 15,
        image: "https://m.media-amazon.com/images/I/61VyJLPSJvL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "The Beatles",
        album: "Sgt. Pepper",
        year: 1967,
        genre: "rock",
        sales: "32 million",
        desc: "Sgt. Pepper's Lonely Hearts Club Band is the eighth studio album by the English rock band the Beatles. Released on 26 May 1967, it spent 27 weeks at number one on the Record Retailer chart in the United Kingdom and 15 weeks at number one on the Billboard Top LPs chart in the United States. The album was lauded by critics for its innovations in songwriting, production and graphic design, for bridging a cultural divide between popular music and high art, and for reflecting the interests of contemporary youth and the counterculture. Its release was a defining moment in 1960s pop culture, heralding the Summer of Love, while the album's reception achieved full cultural legitimisation for pop music and recognition for the medium as a genuine art form.",
        info: "https://en.wikipedia.org/wiki/Sgt._Pepper%27s_Lonely_Hearts_Club_Band"
    }, 
    {
        id: 16,
        image: "https://m.media-amazon.com/images/I/71flezC5C8L._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Various Artists",
        album: "Dirty Dancing",
        year: 1987,
        genre: "pop, rock, r&b",
        sales: "32 million",
        desc: "Dirty Dancing: Original Soundtrack from the Vestron Motion Picture is the original soundtrack to the 1987 film Dirty Dancing. It was released on July 18, 1987, by RCA Records. The album went on to sell 32 million copies worldwide and is one of the best-selling albums of all time. In the United States, the album spent 18 weeks at number one on the Billboard 200 chart and has been certified 11-times Platinum by the Recording Industry Association of America (RIAA). With shipments of at least 3.25 mio. copies, it is the all-time best-selling album in Germany.",
        info: "https://en.wikipedia.org/wiki/Dirty_Dancing_(soundtrack)"
    },
    {
        id: 17,
        image: "https://m.media-amazon.com/images/I/91rQGBRjabL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Michael Jackson",
        album: "Dangerous",
        year: 1991,
        genre: "new jack swing, pop, r&b",
        sales: "32 million",
        desc: "Dangerous is the eighth studio album by American singer Michael Jackson. It was released by Epic Records on November 26, 1991. Co-produced by Jackson, Bill Bottrell, Teddy Riley, and Bruce Swedien, the album was Jackson's first since Forever, Michael (1975) without longtime collaborator Quincy Jones. Featured appearances include Heavy D, Princess Stéphanie of Monaco, Slash and Wreckx-n-Effect. The album incorporates R&B, pop and new jack swing, a growing genre at the time. Elements of industrial, funk, hip hop, electronic, gospel, classical and rock are also featured. Twelve of the album's fourteen songs were written or co-written by Jackson, discussing topics like racism, poverty, romance, self-improvement, and the welfare of children and the world.",
        info: "https://en.wikipedia.org/wiki/Dangerous_(Michael_Jackson_album)"
    },
    {
        id: 18,
        image: "https://m.media-amazon.com/images/I/71W1WoMSWjL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Adele",
        album: "21",
        year: 2011,
        genre: "pop, soul",
        sales: "31 million",
        desc: "21 is the second studio album by English singer-songwriter Adele. It was released on 24 January 2011 in Europe by XL Recordings and on 22 February 2011 in North America by Columbia Records. The album was named after the age of the singer during its production. 21 shares the Motown/soul influences of her 2008 debut album 19, but also draws influence from the American country and Southern blues music that Adele started listening to during the North American leg of her tour An Evening with Adele. Composed in the aftermath of the singer's separation from her then partner, the album explores themes of heartbreak, healing, introspection, and forgiveness.",
        info: "https://en.wikipedia.org/wiki/21_(Adele_album)"
    },
    {
        id: 19,
        image: "https://m.media-amazon.com/images/I/61s2E7maIzL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "The Beatles",
        album: "1",
        year: 2000,
        genre: "rock",
        sales: "31 million",
        desc: "1 is a compilation album by the English rock band the Beatles, originally released on 13 November 2000. The album features virtually every number-one single the band achieved in the United Kingdom or United States from 1962 to 1970. Issued on the 30th anniversary of the band's break-up, it was their first compilation available on only one CD. 1 was a commercial success and topped charts worldwide. It has sold over 31 million copies.",
        info: "https://en.wikipedia.org/wiki/1_(Beatles_album)"
    },
    {
        id: 20,
        image: "https://m.media-amazon.com/images/I/4123ec25vJL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Metallica",
        album: "Metallica",
        year: 1991,
        genre: "heavy metal",
        sales: "31 million",
        desc: "Metallica is the fifth studio album by American heavy metal band Metallica. Released on August 12, 1991, by Elektra Records, it is commonly referred to as The Black Album because of its packaging design. Its recording took place at One on One Studios in Los Angeles over an eight-month span that frequently found Metallica at odds with their new producer Bob Rock. The album marked a change in the band's music from the thrash metal style of their previous four albums to a slower, heavier, and more refined sound.",
        info: "https://en.wikipedia.org/wiki/Metallica_(album)"
    }, 
    {
        id: 21,
        image: "https://m.media-amazon.com/images/I/71usFhs+GPL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Celine Dion",
        album: "Let's Talk About Love",
        year: 1997,
        genre: "pop, soft rock",
        sales: "31 million",
        desc: "Let's Talk About Love is the fifth English-language studio album by Canadian singer Celine Dion, released on 14 November 1997, by Columbia and Epic Records. The follow-up to the commercially successful Falling into You (1996), Let's Talk About Love showed a further progression of Dion's music. Throughout the project, she collaborated with Barbra Streisand, the Bee Gees, Luciano Pavarotti, Carole King, George Martin, Diana King, Brownstone, Corey Hart, and her previous producers: David Foster, Ric Wake, Walter Afanasieff, Humberto Gatica, and Jim Steinman. The album includes Dion's biggest hit, 1My Heart Will Go On'. Written by James Horner and Will Jennings and serving as the love theme for James Cameron's 1997 blockbuster film, Titanic, 'My Heart Will Go On' topped the charts around the world and is considered to be Dion's signature song.",
        info: "https://en.wikipedia.org/wiki/Let%27s_Talk_About_Love"
    },
    {
        id: 22,
        image: "https://m.media-amazon.com/images/I/81dUVKQDBEL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "The Beatles",
        album: "Abbey Road",
        year: 1969,
        genre: "rock",
        sales: "31 million",
        desc: "Abbey Road is the eleventh studio album released by the English rock band the Beatles. It is the last album the group started recording, although Let It Be was the last album completed before the band's dissolution in April 1970. It was mostly recorded in April, July and August 1969, and was released on 26 September 1969 in the United Kingdom, and 1 October 1969 in the United States, reaching number one in both countries. A double A-side single from the album, 'Something' / 'Come Together' was released in October, which also topped the charts in the US.",
        info: "https://en.wikipedia.org/wiki/Abbey_Road"
    },
    {
        id: 23,
        image: "https://m.media-amazon.com/images/I/91BpSjJ3CpL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Guns N' Roses",
        album: "Appetite for Destruction",
        year: 1987,
        genre: "hard rock",
        sales: "30 million",
        desc: "Appetite for Destruction is the debut studio album by American hard rock band Guns N' Roses. It was released on July 21, 1987, by Geffen Records. Appetite for Destruction is the debut studio album by American hard rock band Guns N' Roses. It was released on July 21, 1987, by Geffen Records.",
        info: "https://en.wikipedia.org/wiki/Appetite_for_Destruction"
    }, 
    {
        id: 24,
        image: "https://m.media-amazon.com/images/I/71WszbqivJL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Bruce Springsteen",
        album: "Born in the U.S.A.",
        year: 1984,
        genre: "heartland rock",
        sales: "30 million",
        desc: "Born in the U.S.A. is the seventh studio album by American rock singer-songwriter Bruce Springsteen. It was released by Columbia Records on June 4, 1984. The album's music was written by Springsteen and recorded with his E Street Band and producers Chuck Plotkin and Jon Landau at The Power Station and The Hit Factory in New York City over the course of several years. The process of recording the album was intertwined with that of his previous album, Nebraska. The cover featured an iconic photograph of Springsteen from behind, taken by photographer Annie Leibovitz.",
        info: "https://en.wikipedia.org/wiki/Born_in_the_U.S.A."
    }, 
    {
        id: 25,
        image: "https://m.media-amazon.com/images/I/71kFDTlknuL._AC_UY436_FMwebp_QL65_.jpg",
        artist: "Meat Loaf",
        album: "Bat Out of Hell",
        year: 1977,
        genre: "hard rock",
        sales: "30 million",
        desc: "Bat Out of Hell is the 1977 debut album by American rock singer Meat Loaf and composer Jim Steinman. It is one of the best-selling albums in history. The album was developed from a musical, Neverland, a futuristic rock version of Peter Pan, which Steinman wrote for a workshop in 1974. It was recorded during 1975–1976 at various studios, including Bearsville Studios in Woodstock, New York, produced by Todd Rundgren, and released in October 1977 by Cleveland International/Epic Records. Bat Out of Hell spawned two Meat Loaf sequel albums: Bat Out of Hell II: Back into Hell (1993) and Bat Out of Hell III: The Monster Is Loose (2006).",
        info: "https://en.wikipedia.org/wiki/Bat_Out_of_Hell"
    },                                                                                                                                                                                                                  
]

export default album;